version: "3.5"
services:
  easy:
    build: .
    ports:
      - "3333:3333"
    command: yarn start
    depends_on:
      - db
    volumes:
      - .:/usr/dojo

  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
